# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: chad3814.ZenvikGUI
PackageVersion: 1.3.2
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: zenvik-gui_1.3.2_windows_amd64\zenvik-gui.exe
    PortableCommandAlias: zenvik-gui
  InstallerUrl: https://github.com/chad3814/zenvik/releases/download/v1.3.2/zenvik-gui_1.3.2_windows_amd64.zip
  InstallerSha256: BB8FCF7C330F97F1797977EB1DB3E1A86D3B9BF48B61D0E0E9C2B97EF7A87262
ManifestType: installer
ManifestVersion: 1.12.0
